name: Frozen
main: com.sashavarlamov.mc.frozen.FrozenPlugin
version: 0.0.1-SNAPSHOT
commands:
   freeze:
      description: Makes it so that Anyone Without Armor Will Start Freezing
      usage: /freeze [world], for More Help Type /help frozen
      permission: frozen.freeze
      permission-message: You don't have the freeze permission
   unfreeze:
      description: Stops Freezing the Players Without Armor
      usage: /unfreeze [world], for More Help Type /help frozen
      permission: frozen.unfreeze
      permission-message: You don't have the unfreeze permission
   frozen:
      description: /frozen reload to reload plugin, and /frozen help for help
      usage: /frozen help, or /frozen help
permissions:
   frozen.*:
     description: Gives access to all FreezingColdPlugin commands. It Will Also Make the Player Exempt from Freezing
     children:
       frozen.freeze: true
       frozen.unfreeze: true
       frozen.reload: true
       frozen.exempt: true       
   frozen.freeze:
     description: Allows you to put the world into freezing mode
     default: op
   frozen.unfreeze:
     description: Allows you to unfreeze the world
     default: op
   frozen.reload:
     description: Allows you to reload the config file
     default: op
   frozen.exempt:
     description: A player with this position will not be subject to the world being frozen
     default: op
